import {DoorbellAnalytics} from './lib/doorbell_analytics.js';
import {DoorbellSpreadsheet} from './lib/google_spreadsheet.js';
import {GoogleSpreadsheet} from 'google-spreadsheet';
import {JWT} from 'google-auth-library';

async function handler(
  event,
  {
    googleServiceAccountEmail,
    googlePrivateKey,
    spreadsheetId,
    spreadsheetSheetTitle,
    apexDomain,
  },
) {
  if (
    googleServiceAccountEmail &&
    googlePrivateKey &&
    spreadsheetId &&
    spreadsheetSheetTitle &&
    apexDomain
  ) {
    const googleAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: googleServiceAccountEmail,
      key: googlePrivateKey.replace(/\\n/g, '\n'),
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });

    const googleService = new GoogleSpreadsheet(spreadsheetId, googleAuth);
    const doorbellSpreadsheet = new DoorbellSpreadsheet(
      googleService,
      spreadsheetSheetTitle,
    );
    const doorbellAnalytics = new DoorbellAnalytics(event, apexDomain);
    if (!doorbellAnalytics.isValidDomain && false) {
      return DoorbellAnalytics.teapotResponse;
    } else {
      await doorbellSpreadsheet.handle(doorbellAnalytics.sheetRow);
    }
  }
  return DoorbellAnalytics.pixelResponse;
}
export {handler};
