import {DoorbellAnalytics} from './lib/doorbell_analytics.js';
import {DoorbellSpreadsheet} from './lib/google_spreadsheet.js';
import {GoogleSpreadsheet} from 'google-spreadsheet';
import {JWT} from 'google-auth-library';

async function handler(event) {
  const {
    GOOGLE_SERVICE_ACCOUNT_EMAIL,
    GOOGLE_PRIVATE_KEY,
    SPREADSHEET_ID,
    SPREADSHEET_SHEET_TITLE,
    APEX_DOMAIN,
  } = process.env;
  if (
    GOOGLE_SERVICE_ACCOUNT_EMAIL &&
    GOOGLE_PRIVATE_KEY &&
    SPREADSHEET_ID &&
    SPREADSHEET_SHEET_TITLE &&
    APEX_DOMAIN
  ) {
    const googleAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: GOOGLE_SERVICE_ACCOUNT_EMAIL,
      key: GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });

    const googleService = new GoogleSpreadsheet(SPREADSHEET_ID, googleAuth);
    const doorbellSpreadsheet = new DoorbellSpreadsheet(
      googleService,
      SPREADSHEET_SHEET_TITLE,
    );
    const doorbellAnalytics = new DoorbellAnalytics(event, APEX_DOMAIN);
    if (!doorbellAnalytics.isValidDomain) {
      return DoorbellAnalytics.teapotResponse;
    } else {
      await doorbellSpreadsheet.handle(doorbellAnalytics.sheetRow);
    }
  }
  return DoorbellAnalytics.pixelResponse;
}
export {handler};
